import type { Metadata } from "next";
import { Outfit, Ovo, Roboto } from "next/font/google";
import "./globals.css";
import AuthContextProvider from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";
import EditorContextProvider from "@/context/EditorContext";
import NotificationContextProvider from "@/context/NotificationContext";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Pinterest Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AuthContextProvider>
          <NotificationContextProvider>
            <EditorContextProvider>
              <Toaster />
              {children}
            </EditorContextProvider>
          </NotificationContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
